name: Python Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.11, 3.12, 3.13]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox

    - name: Run tests with tox
      shell: bash
      run: |
        PYTHON_VERSION=${{ matrix.python-version }}
        TOX_ENV="py${PYTHON_VERSION//./}"
        echo "Running tox environment: $TOX_ENV"
        tox -e $TOX_ENV
